name: hive_payments
description: Hive payments created by chocolatoso for hivekings
version: 1.0.0+1
publish_to: none
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.5
  connectivity_plus: ^2.3.6
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  intl: ^0.17.0
  qr_flutter: ^4.0.0
  mobile_scanner: ^3.0.0
  flutter_secure_storage: ^8.0.0
  url_launcher: ^6.1.10
  web_socket_channel: ^2.3.0
  pointycastle: ^3.6.2
  uuid: ^3.0.4
  external_app_launcher: ^3.1.0
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.2.1
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRomanBold.ttf
          weight: 700
        - asset: assets/fonts/RobotoMedium.ttf
          weight: 500
        - asset: assets/fonts/RobotoRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/RobotoRomanBlack.ttf
          weight: 900
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterBold.ttf
          weight: 700
    - family: Archivo
      fonts: 
        - asset: assets/fonts/ArchivoRomanRegular.ttf
          weight: 400
